### ISSUE TITLE
default sketch window size should be canvas size

### ISSUE THREAD

**Issue by antiboredom** [processing/p5.js-editor#132]
when running a sketch the default size of the output window should be the size of the canvas, or the body if other dom elements are present

**Comment by shiffman** [comment]
Also, if you change the size of the canvas, the window should adjust accordingly *unless* you have already manually resized the window, then it stays with your resize?

**Comment by shiffman** [comment]
This is the behavior I'm seeing:

1. `createCanvas(200,200)` -- window auto-set to 200,200
2. I manually resize browser window
3. `createCanvas(300,200)` -- my manual resize is lost and window set to 300,200.

I think once you manually resize we should always keep that size even if you change canvas?  Otherwise, all other scenarios are working great as far as I can tell.

**Comment by antiboredom** [comment]
got it - think it's fixed now.

**Comment by shiffman** [comment]
Great!  Just to be clear, I'm not 100% confident that this is the "correct" behavior.  Just my initial instinct.  We'll see as we get feedback and test!

**Comment by antiboredom** [comment]
Cool - it feels right to me now also - and of course happy to modify later if needed.
