### ISSUE TITLE
Yep! I have been designing a conceptual editor!

### ISSUE THREAD

**Issue by haniuman** [processing/p5.js-editor#199]
Dynamic preview, tabs, colorful themes & many fun features

![p5js-editor-line05](https://cloud.githubusercontent.com/assets/13230502/12210294/e28ca4c8-b626-11e5-9df3-0e0071b3f5f0.png)

**Comment by GiorgioMartini** [comment]
yup looks great...

**Comment by lmccart** [comment]
hey @haniuman this looks very cool, thanks for sharing! i'm trying to clean up the issues a bit here, so i'm going to close this one since it seems to be more of an update than something requiring a fix. if you are looking for more feedback, you might try posting it on the [forum](https://forum.processing.org/two/)
