### ISSUE TITLE
p5 sound not running examples 

### ISSUE THREAD

**Issue by kgrnbrg** [processing/p5.js-editor#88]
when you try to run p5 examples, the browser page that is running the script doesn't load the file but when you try to run the same local host in a different browser the example works.

**Comment by kgrnbrg** [comment]
that's for all the examples

**Comment by kgrnbrg** [comment]
that's for all the sound examples

**Comment by therewasaguy** [comment]
Not sure where this bug came from, but I updated the version of p5.sound on the p5.js github repo to 0.2.12, and if you refresh the editor, everything works... 

sidenote: the editor fetches the latest version of libraries direct from the master branch, but should probably fetch from releases instead. I'll make a separate issue for that.
